Split execCmd to two options
cqfn/save pull request #112
Opened 2021-06-01 09:09 UTC by Cheshiriks

### What's done:
* Split execCmd to two options: one in general config and second in the plugin

Closes #107

2021-06-01 09:55 UTC, petertrr commented on examples/highlevel/suite1/save.toml
> +execFlags = "./detekt --build-upon-default-config -i"
Same here

2021-06-01 15:13 UTC, petertrr requested changes

2021-06-01 15:13 UTC, petertrr commented on examples/highlevel/suite1/save.toml
> +exec_flags="./ktlint -R diktat-0.4.2.jar -F"
This was an invalid example, we can't use different binaries in the same suite. Please remove ktlint from here; to keep example complete, use autofix mode of detekt

2021-06-01 15:13 UTC, petertrr commented on save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt
> +                val execCmd = generalConfig?.execCmd + " " + fixPluginConfig.execFlags
What should we do, if general config is null? I think, we should either raise a warning or use `execFlags` only instead of `execCmd`

2021-06-01 15:13 UTC, petertrr commented on save-plugins/warn-plugin/README.md
> +execFlags = "./detekt --build-upon-default-config -i"
Please change this exampe

2021-06-01 15:13 UTC, petertrr commented on save-plugins/warn-plugin/README.md
> +matching `inputFilePattern`. It will then execute `$exec_flags $testFile` (since we specified
```suggestion
matching `inputFilePattern`. It will then execute `$exec_cmd $exec_flags $testFile` (since we specified
```

2021-06-02 09:21 UTC, akuleshov7 commented on save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt
> +            generalConfig.execCmd + " " + warnPluginConfig.execFlags + " $fileName"
please make a single string

2021-06-02 09:21 UTC, akuleshov7 approved these changes

2021-06-02 09:22 UTC, akuleshov7 approved these changes

2021-06-02 13:23 UTC, petertrr approved these changes

2021-06-03 10:02 UTC, akuleshov7 approved these changes

2021-06-03 12:00 UTC, merged